### ISSUE TITLE
ecl version of cephes.cl fails

### ISSUE THREAD

**Issue by jgarte** [Lisp-Stat/cephes.cl#2]
Hi, the ecl version of cephes.cl fails:

```sh
starting phase `build'
Invoking ecl: "/gnu/store/cawsqjfnnv7qd0qdjq7jmlqp440jqx8m-ecl-21.2.1/bin/ecl" "--eval" "(require :asdf)" "--eval" "(asdf:initialize-source-registry (list :source-registry (list :tree (uiop:ensure-pathname \"/gnu/store/l3jgs39cqb9dgag97dq586c0xxa60jqf-ecl-cephes-1.2-0.d87146f/share/common-lisp/ecl/cephes\" :truenamize t :ensure-directory t)) :inherit-configuration))" "--eval" "(asdf:load-system \"cephes\")" "--eval" "(quit)"
;;; Loading #P"/gnu/store/cawsqjfnnv7qd0qdjq7jmlqp440jqx8m-ecl-21.2.1/lib/ecl-21.2.1/asdf.fas"
Building #P"/gnu/store/l3jgs39cqb9dgag97dq586c0xxa60jqf-ecl-cephes-1.2-0.d87146f/share/common-lisp/ecl/cephes/scipy-cephes/libmd.so"
An error occurred during initialization:
Subprocess with command "make"
 exited with error code 1.
error: in phase 'build': uncaught exception:
%exception #<&invoke-error program: "/gnu/store/cawsqjfnnv7qd0qdjq7jmlqp440jqx8m-ecl-21.2.1/bin/ecl" arguments:
("--eval" "(require :asdf)" "--eval" "(asdf:initialize-source-registry (list :source-registry (list :tree (uiop:ensure-pathname \"/gnu/store/l3jgs39cqb9dgag97dq586c0xxa60jqf-ecl-cephes-1.2-0.d87146f/share/common-lisp/ecl/cephes\" :truenamize t :ensure-directory t)) :inherit-configuration))" "--eval" "(asdf:load-system \"cephes\")" "--eval" "(quit)") exit-status: 1 term-signal: #f stop-signal: #f>
phase `build' failed after 1.2 seconds
```

Is this known to be the case?

Has anyone else tried building cephes.cl with ecl?

**Comment by Symbolics** [comment]
To my knowledge, no one has tried cephes with ecl.  It will definitely work with SBCL, and probably CCL, though support for CCL was dropped some time back due to CCL falling into disrepair.

**Comment by tobyWorland** [comment]
Cephes can be used with ECL (version 21.2.1 at least). See attached.

![Screenshot from 2023-01-20 21-13-16](https://user-images.githubusercontent.com/47527939/213808099-bac14186-d9dc-449c-a50a-52ebb044e3fd.png)

According to your log, it is the `make` that is failing (I believe return code 1 means a rule failed) and since you're using guix, I'm thinking that you're missing a build input.

I'm not too familiar with guix, but I assume there is some guix command to get a shell in the development environment. If you can see if `uname` is there and what happens if you try to run the `make` in the scipy-cephes directory yourself.

---

As far as I know, the only lisp-stat system dependent on `sbcl` is `data-frames`.

**Comment by jgarte** [comment]
I'll try again soon and let you know if I was able to fix it. Thanks for the report and helping out with debugging the Guix package! It's much appreciated.

Here's the patch series for all of lisp-stat:

https://issues.guix.gnu.org/60835

> As far as I know, the only lisp-stat system dependent on sbcl is data-frames.

Interesting! Do you happen to know why `sbcl` is dependent on `data-frames`

**Comment by Symbolics** [comment]
> Interesting! Do you happen to know why `sbcl` is dependent on `data-frames`

It's nothing major.  It's because we use a CLTL2 environment feature to help in formatting printed output.  Other implementions may have CLTL2 functions available too, but they haven't been investigated.

**Comment by snunez1** [comment]
Closing because there hasn't been any activity for a while.  If desired, please reopen and we'll try to help.
